version: 2.1
executors:
  buildpack:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  deploy-nginx:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build nginx container
          command: |
            make build_or_publish WORKSPACE="${CIRCLE_BRANCH}"

workflows:
  version: 2

  build:
    jobs:
      - deploy-nginx
